version: "3"
services:
  mongo1:
    container_name: mongo1
    build:
      context: ./mongo
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.mongo-variables
    environment:
      - MONGO_INITDB_ROOT_USERNAME= '${MONGO_INITDB_ROOT_USERNAME}'
      - MONGO_INITDB_ROOT_PASSWORD= '${MONGO_INITDB_ROOT_PASSWORD}'
    volumes:
      - ./mongo/data1:/data/db
    networks:
      - smart-cart-network
      - mongo-network
    ports:
      - 27017:27017
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 3s
      retries: 3

  mongo2:
    container_name: mongo2
    build:
      context: ./mongo
      dockerfile: Dockerfile.dev
    volumes:
      - ./mongo/data2:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - mongo-network
      - smart-cart-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 3s
      retries: 3

  mongo3:
    container_name: mongo3
    build:
      context: ./mongo
      dockerfile: Dockerfile.dev
    volumes:
      - ./mongo/data3:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - mongo-network
      - smart-cart-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  data1: {}
  data2: {}
  data3: {}

networks:
  mongo-network:
    driver: bridge
  smart-cart-network:
    external: true
    name: smart-cart-network
