version: "3"
services:
  mongo1:
    container_name: mongo1
    image: mongo:latest
    env_file:
      - ./.env.mongo-variables
    environment:
      - MONGO_INITDB_ROOT_USERNAME= adminUser
      - MONGO_INITDB_ROOT_PASSWORD= adminPass
    volumes:
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
      - ./mongo/data1:/data/db
      - ./mongo/key/keyfile.key:/key/keyfile.key
    networks:
      - smart-cart-network
      - mongo-network
    ports:
      - 27017:27017
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--keyFile",
        "/key/keyfile.key",
        "--replSet",
        "dbrs",
        "--bind_ip_all",
      ]

  mongo2:
    container_name: mongo2
    image: mongo:latest
    env_file:
      - ./.env.mongo-variables
    environment:
      - MONGO_INITDB_ROOT_USERNAME= adminUser
      - MONGO_INITDB_ROOT_PASSWORD= adminPass
    volumes:
      - ./mongo/data2:/data/db
      - ./mongo/key/keyfile.key:/key/keyfile.key
    ports:
      - 27018:27017
    restart: always
    networks:
      - mongo-network
    entrypoint:
      [
        "/usr/bin/mongod",
        "--keyFile",
        "/key/keyfile.key",
        "--replSet",
        "dbrs",
        "--bind_ip_all",
      ]

  mongo3:
    container_name: mongo3
    image: mongo:latest
    env_file:
      - ./.env.mongo-variables
    environment:
      - MONGO_INITDB_ROOT_USERNAME= adminUser
      - MONGO_INITDB_ROOT_PASSWORD= adminPass
    volumes:
      - ./mongo/data3:/data/db
      - ./mongo/key/keyfile.key:/key/keyfile.key
    ports:
      - 27019:27017
    restart: always
    networks:
      - mongo-network
    entrypoint:
      [
        "/usr/bin/mongod",
        "--keyFile",
        "/key/keyfile.key",
        "--replSet",
        "dbrs",
        "--bind_ip_all",
      ]

volumes:
  mongo1: {}
  mongo2: {}
  mongo3: {}

networks:
  mongo-network:
    driver: bridge
  smart-cart-network:
    external: true
    name: smart-cart-network
