version: '3.9'
services:
  mongo1:
    container_name: mongo1
    image: mongo:latest
    env_file:
      - mongo-variables.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME= ${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD= ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./scripts/mongo/rs-init.sh:/scripts/rs-init.sh
      - ./scripts/mongo/init.js:/scripts/init.js
      - ./mongo/data1:/data/db
      - ./mongo/key/keyfile.key:/data/keyfile.key
    networks:
      - api-network
      - mongo-network
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod" ,"--keyFile", "/data/keyfile.key", "--replSet", "dbrs","--bind_ip_all"]


  mongo2:
    container_name: mongo2
    image: mongo:latest
    env_file:
      - mongo-variables.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME= ${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD= ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo/data2:/data/db
      - ./mongo/key/keyfile.key:/data/keyfile.key
    ports:
      - 27018:27017
    restart: always
    networks:
      - mongo-network
    entrypoint: [ "/usr/bin/mongod" ,"--keyFile", "/data/keyfile.key", "--replSet", "dbrs","--bind_ip_all"]


  mongo3:
    container_name: mongo3
    image: mongo:latest
    env_file:
      - mongo-variables.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME= ${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD= ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo/data3:/data/db
      - ./mongo/key/keyfile.key:/data/keyfile.key
    ports:
      - 27019:27017
    restart: always
    networks:
      - mongo-network
    entrypoint: [ "/usr/bin/mongod" ,"--keyFile", "/data/keyfile.key", "--replSet", "dbrs","--bind_ip_all"]


volumes:
  mongo1: {}
  mongo2: {}
  mongo3: {}


networks:
  mongo-network:
    driver: bridge
  api-network:
    external: true
    name: api-network
