version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: always
    networks:
      - smart-cart-network
    env_file:
      - ./api/.env.development
    volumes:
      - /usr/src/app/node_modules
      - ./api:/usr/src/app
    expose:
      - 7743

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    networks:
      - smart-cart-network
    depends_on:
      - api
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    environment:
      - WDS_SOCKET_PORT=0
    expose:
      - 3000

  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - api
      - frontend
    networks:
      - smart-cart-network
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
networks:
  smart-cart-network:
    external: true
    name: smart-cart-network
