version: "3"
services:
  mongo1:
    container_name: mongo1
    image: mongo:latest
    env_file:
      - ./.env.mongo-variables
    environment:
      - MONGO_INITDB_ROOT_USERNAME= ${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD= ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
      - ./mongo/data1:/data/db
    networks:
      - smart-cart-network
      - mongo-network
    ports:
      - 27017:27017
    restart: unless-stopped
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]

  mongo2:
    container_name: mongo2
    image: mongo:latest
    env_file:
      - ./.env.mongo-variables
    environment:
      - MONGO_INITDB_ROOT_USERNAME= ${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD= ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo/data2:/data/db
    ports:
      - 27018:27018
    restart: unless-stopped
    networks:
      - mongo-network
      - smart-cart-network
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]

  mongo3:
    container_name: mongo3
    image: mongo:latest
    env_file:
      - ./.env.mongo-variables
    environment:
      - MONGO_INITDB_ROOT_USERNAME= ${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD= ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo/data3:/data/db
    ports:
      - 27019:27019
    restart: unless-stopped
    networks:
      - mongo-network
      - smart-cart-network
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]

volumes:
  data1: {}
  data2: {}
  data3: {}

networks:
  mongo-network:
    driver: bridge
  smart-cart-network:
    external: true
    name: smart-cart-network
