version: '3.9'
services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    restart: always
    networks:
      - api-network
      - redis-network
    env_file:
      - redis.env
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379

  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    restart: always
    depends_on:
      - redis-master
    networks:
      - redis-network
    command: redis-server  --slaveof redis-master 6379
    

  redis-slave2:
    image: redis:latest
    restart: always
    container_name: redis-slave2
    depends_on:
      - redis-master
    networks:
      - redis-network
    command: redis-server --slaveof redis-master 6379
    

networks:
  redis-network:
    driver: bridge
  api-network:
    external: true
    name: api-network
volumes:
  redis: {}