apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: smart-cart-pool
  namespace: metallb-system
spec:
  addresses:
    - 127.0.10.200-127.0.10.203

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
