name: Smart-Cart images
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: docker hub login
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build images
        run: |-
          docker build -t grady305/smart-cart-api:latest -t grady305/smart-cart-api:${{ env.SHA }} -f ./api/Dockerfile ./api
          docker build -t grady305/smart-cart-frontend:latest -t grady305/smart-cart-frontend:${{ env.SHA }} -f ./frontend/Dockerfile ./frontend
          docker build -t grady305/smart-cart-nginx:latest -t grady305/smart-cart-nginx:${{ env.SHA }} -f ./nginx/Dockerfile ./nginx

      - name: Push images
        run: |-
          docker push grady305/smart-cart-api:latest
          docker push grady305/smart-cart-frontend:latest
          docker push grady305/smart-cart-nginx:latest

          docker push grady305/smart-cart-api:${{ env.SHA }}
          docker push grady305/smart-cart-frontend:${{ env.SHA }}
          docker push grady305/smart-cart-nginx:${{ env.SHA }}

      - name: Apply k8s manifest
        run: |-
          kubectl set image deployments/api-deployment api=grady305/smart-cart-api:${{ env.SHA }}
          kubectl set image deployments/frontend-deployment frontend=grady305/smart-cart-frontend:${{ env.SHA }}
